# select distinct ?item  ?itemDescription ?sitelinks where {
#     ?item wdt:P31 wd:Q5;  # Any instance of a human.
#           wdt:P19 wd:Q60;  #  Who was born in New York City.
# # Note. Doesn't include humans with the birth place listed as a hospital
# # or an administrative area or other location of New York City.
# # Only humans listed as born in New York City. 
#              wikibase:sitelinks ?sitelinks.
   
# }
# ORDER BY DESC(?sitelinks)