# #defaultView:ScatterChart
# PREFIX var_muntype: <http://www.wikidata.org/entity/Q15284>
# PREFIX var_area: <http://www.wikidata.org/entity/Q6308>
# SELECT ?from (?distNum AS ?kilometers) ?to (?distGrp AS ?animation) WHERE {
#   { SELECT ?mun (SAMPLE(?loc) AS ?loc)
#     WHERE { ?mun wdt:P31/wdt:P279* var_muntype:;
#                  wdt:P131 var_area:;
#                  wdt:P625 ?loc. }
#     GROUP BY ?mun
#   }
#   OPTIONAL {
#     { SELECT (?mun AS ?mun2) (SAMPLE(?loc) AS ?loc2)
#       WHERE { ?mun wdt:P31/wdt:P279* var_muntype:;
#                    wdt:P131 var_area:;
#                    wdt:P625 ?loc. }
#       GROUP BY ?mun
#     }
#   }
#   #FILTER (STR(?mun) <= STR(?mun2)).
#   BIND(geof:distance(?loc, ?loc2) AS ?distNum).
#   BIND(COALESCE(
#     IF(?distNum >= 40, "40 km und mehr", 1/0),
#     IF(?distNum >= 30, "30 - 40 km", 1/0),
#     IF(?distNum >= 20, "20 - 30 km", 1/0),
#     IF(?distNum >= 10, "10 - 20 km", 1/0),
#     IF(?distNum >= 5, "05 - 10 km", 1/0),
#     IF(?distNum >= 1, "01 - 05 km", "00 - 01 km")) AS ?distGrp).
  
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en".
#     ?mun rdfs:label ?from.
#     ?mun2 rdfs:label ?to.
#   }
# }
# ORDER BY ?animation ?from ?kilometers