# SELECT DISTINCT ?item ?name ?coord ?lat ?lon ?globe
# {
#    ?item wdt:P31 wd:Q429088 ;
#          p:P625 [
#            psv:P625 [
#              wikibase:geoLatitude ?lat ;
#              wikibase:geoLongitude ?lon ;
#              wikibase:geoGlobe ?globe ;
#            ] ;
#            ps:P625 ?coord
#          ]
#   FILTER ( ?globe != wd:Q2 )
# }
# ORDER BY ASC (?name)