#Elevations over 8000 (meter, feet or other)
#Note the absence of units and the presence of coordinates
#Last updated 2021-04-25

SELECT ?elevation ?item  ?itemDescription ?coord
WHERE
{
  ?item wdt:P2044 ?elevation .
  filter(?elevation > 8000)
  ?item wdt:P625 ?coord .
  
}
ORDER BY DESC(?elevation)