# #Concise list & map of the 355 Dutch municipalities, their geo coordinates and their provinces, per 1-1-2019
# #See also: 
# #https://almanak.overheid.nl/organisaties/Gemeenten/ - 355 in aantal
# #https://nl.wikipedia.org/wiki/Lijst_van_Nederlandse_gemeenten - 355 in aantal

# #defaultView:Map
# select ?muni ?muniLabel ?location where {
#   ?muni p:P31 ?instanceOf; # Get statement because we need this later
#         wdt:P625 ?location. # And location
#   ?instanceOf ps:P31 wd:Q2039348. # P31 should be 'municipality of the Netherlands'
#   minus { ?muni wdt:P31 wd:Q7265977. } # Don't show former municipalities
#   minus { ?instanceOf pq:P582 ?endTime. } # And don't show municipalities that have an end time
#   service wikibase:label { bd:serviceParam wikibase:language "nl". } # Show names in Dutch
# }