# #title: Items about authors with a Wikispecies page
# SELECT ?author ?authorLabel (COUNT(?paper) AS ?count)
# WHERE
# {
#   ?article  schema:about ?author ;
#       schema:isPartOf <https://species.wikimedia.org/> .
#     ?author wdt:P31 wd:Q5.
#     ?paper wdt:P50 ?author.
#   
# }
# GROUP BY ?author ?authorLabel
# ORDER BY DESC(?count)
# LIMIT 200