# #defaultView:Map{"hide":["?atm","?geometry"], "layer": "?bankLabel"}

# PREFIX lgdo: <http://linkedgeodata.org/ontology/>
# PREFIX geom: <http://geovocab.org/geometry#>
# PREFIX bif: <bif:>

# SELECT ?atm ?geometry ?bank ?bankLabel WHERE {
#   hint:Query hint:optimizer "None".
  
#   SERVICE <http://linkedgeodata.org/sparql> {
#     { ?atm a lgdo:Bank; lgdo:atm true. }
#     UNION { ?atm a lgdo:Atm. }
    
#     ?atm geom:geometry [geo:asWKT ?geometry];
#          lgdo:operator ?operator.
#     FILTER(bif:st_intersects(?geometry, bif:st_point(11.5746898, 48.1479876), 5)) # 5 km around Munich
#   }
  
#   BIND(STRLANG(?operator, "de") as ?bankLabel) 
#   ?bank rdfs:label ?bankLabel.
  
#   # bank is part of the Bankcard service network, either via an explicit statement or implicitly due to its legal form (unless explicitly excluded)
#   { ?bank wdt:P527 wd:Q806724. }
#   UNION { ?bank wdt:P1454 wd:Q5349747. }
#   MINUS { wd:Q806724 wdt:P3113 ?bank. }
# }