# SELECT ?place ?location ?distance ?placeLabel WHERE {
#     SERVICE wikibase:around { 
#       ?place wdt:P625 ?location . 
#       bd:serviceParam wikibase:center "Point(-122.402251 37.789246)"^^geo:wktLiteral . 
#       bd:serviceParam wikibase:radius "1" . 
#       bd:serviceParam wikibase:distance ?distance .
#     } 
    
# } ORDER BY ?distance LIMIT 100