# #by Jura1, 2021-05-21
# #defaultView:Map{"hide":["?coor","?area_scale_km"], "layer": "?area_scale_km"}
# SELECT ?item  ?itemDescription ?coor ?area_sqkm ?area_scale_km
# {
# 	?item wdt:P31/wdt:P279* wd:Q35666 . 
#     OPTIONAL { ?item wdt:P625 ?coor }
#     OPTIONAL { ?item p:P2046 [ a wikibase:BestRank; psn:P2046/wikibase:quantityAmount ?area_sqm ] . 
#               BIND( ROUND(?area_sqm/10000)/100 as ?area_sqkm)
#               BIND( strlen(str(ROUND(?area_sqm/1000000))) as ?area_scale_km)
#              }  
	
# }