# PREFIX pr: <http://www.wikidata.org/prop/reference/>
# PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
# PREFIX prov: <http://www.w3.org/ns/prov#>

# SELECT ?compound ?doi ?wpid WHERE {
#   ?compound wdt:P31 wd:Q11173.
#   MINUS { ?compound wdt:P31 wd:Q8054. }
#   ?compound p:P703 ?statement.
#   ?statement rdf:type wikibase:BestRank.
#   ?statement ps:P703 ?species.
#   OPTIONAL {
#     ?statement (prov:wasDerivedFrom/pr:P248) ?source.
#     OPTIONAL { ?source wdt:P2410 ?wpid. }
#     OPTIONAL { ?source wdt:P356 ?doi. }
#   }
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
# }
# ORDER BY ASC(?compound)