SELECT DISTINCT ?idExtension ?extension ?mediaType
WHERE
{
  ?idExtension wdt:P31 wd:Q235557
  ; wdt:P1195 ?extension .
  OPTIONAL { ?idExtension wdt:P1163 ?mediaType }
}
ORDER BY ?extension ?mediaType