#defaultView:BubbleChart 
#title:Software applications ranked in descending order by the number of writable file formats
SELECT ?app (COUNT(?format) AS ?count)
WHERE {
  ?app (p:P31/ps:P31/wdt:P279) wd:Q7397 .
  ?app wdt:P1072 ?format .

  }

GROUP BY ?app
ORDER BY DESC(?count)