#two chemical compounds with the same CAS registry number
SELECT DISTINCT ?cas ?compound1 ?compound2 WHERE {
  ?compound1 wdt:P231 ?cas .
  ?compound2 wdt:P231 ?cas .
  FILTER (?compound1 != ?compound2)
}