SELECT
  ?discoverer ?discovererLabel 
  (COUNT(DISTINCT ?planet) as ?count)
  (GROUP_CONCAT(DISTINCT(?planetLabel); separator=", ") as ?planets)
WHERE
{
  ?ppart wdt:P279* wd:Q634 .
  ?planet wdt:P31 ?ppart .
  ?planet wdt:P61 ?discoverer .
}
GROUP BY ?discoverer ?discovererLabel
ORDER BY DESC(?count)