# #title: Mayors that are any kind of domesticated animal
# SELECT ?image ?speciesLabel ?placeLabel WHERE {
#   ?species wdt:P279* wd:Q622852 .
#   ?mayor wdt:P31 ?species . 
 
#   ?mayor p:P39 ?node .
#   ?node ps:P39 wd:Q30185 .
#   ?node pq:P642 ?place .
#   optional{?mayor wdt:P18 ?image}
  
# }