#added 2016-12
##defaultView:BubbleChart
SELECT ?author (COUNT(?publication) AS ?count)
WHERE
{
    ?item wdt:P2860 ?publication . #citations
    ?publication wdt:P50 ?author . #authors
    ?author wdt:P21 wd:Q6581072. #females
}
GROUP BY ?author
ORDER BY DESC(?count)