# SELECT (COUNT (?statement) as ?statements)
# WHERE
# {
#   ?entry ?p ?statement .
#   ?statement prov:wasDerivedFrom/
#        <http://www.wikidata.org/prop/reference/P248>/
#        wdt:P356 ?doi .
# }