# SELECT ?image ?speciesLabel ?mayorLabel ?placeLabel WHERE {
#   VALUES ?species {wd:Q144 wd:Q146 wd:Q780}
#   ?mayor wdt:P31 ?species .
#   ?mayor p:P39 ?node .
#   ?node ps:P39 wd:Q30185 .
#   ?node pq:P642 ?place .
#   optional{?mayor wdt:P18 ?image}
  
# }