# SELECT ?English  WHERE {
#   ?disease wdt:P699 "DOID:399"/
#   BIND(LANG(?label) as ?languageCode)
#   ?wdLanguage wdt:P424 ?languageCode;
#               rdfs:label ?language .
#     FILTER EXISTS {?wdLanguage wdt:P31?/wdt:P279+ wd:Q17376908}        
# }