#defaultView:Timeline
SELECT
  ?theorem
  ?nameLabel
  ?death
  ?formula
WHERE {
  ?theorem wdt:P31  wd:Q65943;
           wdt:P138 ?name.
  ?name    wdt:P570 ?death;
           wdt:P21  ?gender .
  # OPTIONAL{
  ?theorem wdt:P2534 ?formula.
  # }
}
ORDER BY DESC(?death)
LIMIT 100