SELECT ?h ?location (CONCAT("injured: ",str(?injured)) as ?injuredl) (concat("dead: ",str(?dead)) as ?deadl) ?date ?image
WHERE
{
        ?h wdt:P31 ?attack. 
    values (?attack) {
      (wd:Q18493502)
      (wd:Q217327)
     
     
    }
    optional {    ?h wdt:P1339 ?injured . }
    optional {    ?h wdt:P1120 ?dead. }
    optional {    ?h wdt:P276?/wdt:P625 ?location }
    optional {    ?h wdt:P585 ?date }
    optional {    ?h wdt:P18 ?image }
}