# SELECT distinct ?book ?bookLabel ?authorLabel (GROUP_CONCAT(?genre_label) as ?genres) (MIN(?publicationDate) as ?firstPublication)
# WHERE
# {
#   ?author rdfs:label "Ernest Hemingway"@en .
#   ?book wdt:P50 ?author .
#   OPTIONAL {
#     ?book wdt:P136 ?genre .
#     ?genre rdfs:label ?genre_label filter (lang(?genre_label) = "en").
#   }

#   OPTIONAL {
#     ?book wdt:P577 ?publicationDate .
#   }
#   SERVICE wikibase:label {
#     bd:serviceParam wikibase:language "en" .
#   }
# } group by ?book ?bookLabel ?authorLabel