# SELECT ?s ?desc (COUNT(DISTINCT ?label) as ?labelcount)
# WHERE
# {
#   ?s wdt:P31 wd:Q37484 .
#   ?s rdfs:label ?label .
#   OPTIONAL {
#      ?s rdfs:label ?desc filter (lang(?desc) = "en").
#    }
#  } GROUP BY ?s ?desc ORDER BY DESC(?labelcount)