# #title:All forms in Swedish missing a pronunciation for the form with a representation identical to the lemma of the lexeme
# # So9q 13-01-2021
# SELECT ?l ?lemma ?form ?audio WHERE {
#   ?l dct:language wd:Q9027;
#      wikibase:lemma ?lemma; 
#      ontolex:lexicalForm ?form .
#   ?form ontolex:representation ?lemma .
#   minus {?form wdt:P443 ?audio.}
# }