select ?translator ?work ?workLabel ?author {  
    ?work wdt:P655 ?translator;        
          wdt:P50 ?author.    

    ?author wdt:P2533 ?wid;          
            wdt:P21 wd:Q6581072;          
            wdt:P569 ?birth;            

    filter (?birth > "1800-01-01"^^xsd:dateTime && ?birth < "1900-01-01"^^xsd:dateTime)

}