# added in 2017-06
#defaultView:ImageGrid
SELECT ?item  ?object ?image
WHERE
{
  ?item wdt:P31/wdt:P279* wd:Q3305213 .  
  ?item wdt:P180 ?object .
  ?object wdt:P279* wd:Q181247 . 
  ?item wdt:P18 ?image .
}