# # Lexemes in English with picture and description fetched from the concept Q-item
# # NB: when 2 or more pictures occur for the same lemma a preferred rank is missing on the Q-item. 
# # Please fix that if you know how.
# # by So9q
# #defaultView:ImageGrid
# select distinct ?lexemeId ?lemma ?q_concept ?q_conceptDescription ?picture 
# WHERE {
#   ?lexemeId dct:language wd:Q1860;
#             wikibase:lemma ?lemma;
#             ontolex:sense ?sense.
#   ?sense wdt:P5137 ?q_concept.
#   ?q_concept wdt:P18 ?picture.
#   # if you wish to only browse certain items you can insert a FILTER 
#   # regular expression here, like in the example above.
  
# }
# order by lcase(?lemma) # order a-z