# SELECT
#   ?item
#   (SAMPLE (?titleL) AS ?title)
#   (group_concat(distinct ?creatorL ; separator = ", ") as ?creator)
#   (group_concat(distinct ?genreL ; separator = ", ") as ?genre)
#   (group_concat(distinct ?placeL ; separator = ", ") as ?place)
#   (group_concat(distinct ?arr ; separator = ", ") as ?arrondissement)
#   (SAMPLE (?img) AS ?image)
#   (SAMPLE (?coord) AS ?coordinates) {

#     {
#       SELECT DISTINCT ?item { {
#         ?item wdt:P136 wd:Q557141 ;     # genre: public art
#               wdt:P131 wd:Q90           # located in: Paris
#       } UNION { # or
#         ?item wdt:P136 wd:Q557141 ;     # genre: public art
#               wdt:P131/wdt:P131* wd:Q90 # located in an arrondissement of Paris
#       } }
#     }
   
#     # title
#     OPTIONAL { ?item rdfs:label ?titleL filter (lang(?titleL) = "fr") }
   
#     # creators
#     OPTIONAL { ?item wdt:P170 [rdfs:label ?creatorL] filter (lang(?creatorL) = "fr") }
   
#     #genre
#     OPTIONAL {
#       {
#         ?item wdt:P136 ?g filter (STR(?g) != 'http://www.wikidata.org/entity/Q557141')
#       } UNION {
#         ?item wdt:P31 ?g .
#       }
#       ?g rdfs:label ?genreL filter (lang(?genreL) = "fr") .
#     }
   
#     # place
#     OPTIONAL {
#       ?item wdt:P276 [rdfs:label ?placeL] filter (lang(?placeL) = "fr") .
#     }
   
#     # arrondissement
#     OPTIONAL {
#       ?item wdt:P131 [wdt:P131 wd:Q90 ; rdfs:label ?arrL] filter (lang(?arrL) = "fr").
#       BIND(REPLACE(?arrL, '^([0-9]+).*$', "$1", "si") AS ?arr)
#     }
   
#     # image
#     OPTIONAL { ?item wdt:P18 ?img }
   
#     # coordinates
#     OPTIONAL { ?item wdt:P625 ?coord }

# } GROUP BY ?item