# SELECT ?doi (count(?doi) as ?counts) WHERE {
#    ?statement prov:wasDerivedFrom ?ref . 
#    ?ref pr:P356 ?doi .
#    FILTER (CONTAINS(lcase(?doi), "figshare"))   
# }
# GROUP BY ?doi
# ORDER BY DESC(?counts)