# SELECT DISTINCT ?item  ?_PubMed_ID
# WHERE
# {
#   ?item wdt:P31 wd:Q13442814 ;
#         rdfs:label  .
#   OPTIONAL { ?item wdt:P698 ?_PubMed_ID. }
#   FILTER(CONTAINS(LCASE(), "zika"))
#   FILTER (LANG()="en")
# }