# # By So9q
# # Lexemes that means (liquid) water
# select ?l ?sense ?lemma ?languageLabel WHERE {
#   ?l a ontolex:LexicalEntry ; # get from the special LexicalEntry
#        ontolex:sense ?sense ; # the sense
#        dct:language ?language ; # the language
#        wikibase:lemma ?lemma. # and the lemma
#   ?sense wdt:P5137 wd:Q29053744 .
#                    # change Q29053744 to anything you want 
  
# }
# # Lower case before order
# order by (LCASE(?languageLabel))