# # by So9q, 2019-11-21
# # no known limitations

# #defaultView:BubbleChart
# SELECT ?meaning ?meaningLabel (count(?l) as ?count) 
# WHERE {
#    ?l a ontolex:LexicalEntry ; 
#         ontolex:sense ?sense. # get the sense
#   ?sense wdt:P5137 ?meaning. #extract the meaning
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en"}
# }
# group by ?meaning ?meaningLabel # 2 here to avoid "bad aggregate", see https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial#Painting_materials
# order by desc(?count) # rank by the most translated concepts 
# limit 100 # only show the 100 highest to avoid clutter