# # Forms of nouns in Hebrew that are both feminine and masculine
# # e.g. ???
# # by Uziel302
# select ?lexemeId ?lemma ?form ?word WHERE {
#   ?lexemeId dct:language wd:Q9288;
#             wikibase:lexicalCategory wd:Q1084;
#             wikibase:lemma ?lemma.
#   ?lexemeId ontolex:lexicalForm ?form .
#   ?form wikibase:grammaticalFeature wd:Q499327;
#         wikibase:grammaticalFeature wd:Q1775415;
#         ontolex:representation ?word .
# }