# select ?p ?pLabel (count (*) as ?count) {
#   ?s ?pd ?o .
#   ?p wikibase:directClaim ?pd .
#   ?s wdt:P31/wdt:P279* wd:Q729 .
#   ?o wdt:P31/wdt:P279* wd:Q43501 .
  
# } group by ?p ?pLabel order by desc(?count)