# #Show titles of articles about Ukrainian villages on Romanian Wikipedia, plus English and Ukrainian labels in Wikidata items
# #added in 2017-05
# SELECT DISTINCT ?item ?LabelEN ?LabelUK ?page_titleRO WHERE {
#   ?item wdt:P31 wd:Q532 .  
#   ?item wdt:P17 wd:Q212 .
#   ?article schema:about ?item ; schema:isPartOf <https://ro.wikipedia.org/> ;  schema:name ?page_titleRO .
#   ?item rdfs:label ?LabelEN filter (lang(?LabelEN) = "en") .
#   ?item rdfs:label ?LabelUK filter (lang(?LabelUK) = "uk") .
# }
# LIMIT 300