# SELECT ?item ?comm ?p373 ?cat WHERE {
#   ?item wdt:P131* wd:Q894107.                               # ... municipality ...

#   optional {?comm schema:about ?item ; schema:isPartOf <https://commons.wikimedia.org/> .}
#   BIND(replace(wikibase:decodeUri(SUBSTR(STR(?comm), 45)),"_"," ") AS ?comm_decode)
#    optional {?item wdt:P373 ?p373 .}
  
#  bind(COALESCE(?comm_decode, ?p373) as ?cat) .
#  VALUES ?trida { wd:Q1746392 wd:Q108325 wd:Q4989906 wd:Q10861631 wd:Q15077340 wd:Q1516537 wd:Q47008262}     # chapel, small monument, memorial, belltower, memorial monument, technical monument,  group of small monuments 
#  ?item wdt:P31/wdt:P279* ?trida.                  #  small monument
#   }