# # Get all Featured Articles (Q17437796)
# SELECT ?lang ?name  ?sitelink ?linkcount ?item WHERE {
#   ?item wikibase:sitelinks ?linkcount.
#   ?sitelink schema:name ?name;
#     schema:inLanguage ?lang;
#     schema:about ?item;
#     # Sitelink is badged as a Featured Article
#     wikibase:badge wd:Q17437796.
  
# }