# # Updated 2020-06-17

# # Gotta catch 'em all
# SELECT DISTINCT ?pokemon ?pokemonLabel ?pokedexNumber
# WHERE
# {
#     ?pokemon wdt:P31/wdt:P279* wd:Q3966183 .
#     ?pokemon p:P1685 ?statement.
#     ?statement ps:P1685 ?pokedexNumber;
#               pq:P972 wd:Q20005020.
#     FILTER (! wikibase:isSomeValue(?pokedexNumber) )
#     
# }
# ORDER BY (?pokedexNumber)