# SELECT DISTINCT ?episode ?ordinal ?episodeLabel ?subject ?subjectLabel
# WHERE {
#   ?episode wdt:P31/wdt:P279* wd:Q1983062;
#            p:P179 ?statement.
#   OPTIONAL{ ?episode wdt:P921 ?subject }
#   ?statement ps:P179 wd:Q3577037;
#              pq:P1545 ?ordinal
  
# } ORDER BY xsd:integer(?ordinal)