# #added 2017-07-16, updated 2020-07-08
# SELECT ?doctor ?doctorLabel ?ordinal ?performer ?performerLabel
# WHERE {
#   ?doctor wdt:P31 wd:Q47543030 .
#   OPTIONAL { ?doctor wdt:P1545 ?ordinal }
#   OPTIONAL { ?doctor p:P175 / ps:P175 ?performer }
#   
# }
# ORDER BY ASC(xsd:integer(?ordinal) )