#defaultView:Map
SELECT ?connectsairport ?place_served ?coor
WHERE
{
  VALUES ?airport { wd:Q17480 } # Antwerp international airport  wd:Q17480
  ?airport wdt:P81 ?connectsairport ;
           wdt:P625 ?base_airport_coor .
  ?connectsairport wdt:P931 ?place_served ;
                   wdt:P625 ?coor .
 
}