# PREFIX entity: <http://www.wikidata.org/entity/>

# #  In addition to the original query this one comes with some advantages:
# #  - You will get only literals as results, (even if the values are stored as IRI in wikibase)
# #  - That means you will also get properties as birth date, alphanumeric identifier and so on.
# #  - The list is ordered numerically by property number. (So P19 comes before P100) 
# #  - All label, altLabel and description in a given Language are included.
# #  You may open a separate column ?valUrl if you need also the IRI
# #
# #  Please advise, if there is an option to put the Q-Number  and/or the Language 
# #  code into a runtime variable. 

# SELECT ?propNumber ?propLabel ?val
# WHERE
# {
# 	hint:Query hint:optimizer 'None' .
# 	{	BIND(entity:Q42 AS ?valUrl) .
# 		BIND("N/A" AS ?propUrl ) .
# 		BIND("Name"@de AS ?propLabel ) .
#        entity:Q42 rdfs:label ?val .
      
#         FILTER (LANG(?val) = "de") 
# 	}
#     UNION
#     {   BIND(entity:Q42 AS ?valUrl) .
      
#         BIND("AltLabel"@de AS ?propLabel ) .
#         optional{entity:Q42 skos:altLabel ?val}.
#         FILTER (LANG(?val) = "de") 
#     }
#     UNION
#     {   BIND(entity:Q42 AS ?valUrl) .
      
#         BIND("Beschreibung"@de AS ?propLabel ) .
#         optional{entity:Q42 schema:description ?val}.
#         FILTER (LANG(?val) = "de") 
#     }
#    	UNION
# 	{	entity:Q42 ?propUrl ?valUrl .
# 		?property ?ref ?propUrl .
# 		?property rdf:type wikibase:Property .
# 		?property rdfs:label ?propLabel.
#      	FILTER (lang(?propLabel) = 'de' )
#         filter  isliteral(?valUrl) 
#         BIND(?valUrl AS ?val)
# 	}
# 	UNION
# 	{	entity:Q42 ?propUrl ?valUrl .
# 		?property ?ref ?propUrl .
# 		?property rdf:type wikibase:Property .
# 		?property rdfs:label ?propLabel.
#      	FILTER (lang(?propLabel) = 'de' ) 
#         filter  isIRI(?valUrl) 
#         ?valUrl rdfs:label ?valLabel 
# 		FILTER (LANG(?valLabel) = "de") 
#          BIND(CONCAT(?valLabel) AS ?val)
# 	}
#         BIND( SUBSTR(str(?propUrl),38, 250) AS ?propNumber)
# }
# ORDER BY xsd:integer(?propNumber)