# # This query collects data related to entities on Barbara Harris. 
# # It demonstrates collecting individual attributes and concatenating them for easier post processing. 

# SELECT 
#   ?item
# (SAMPLE(?itemDescription) AS ?itemDescription) 
#   (SAMPLE(?pic) AS ?pic) 
# (SAMPLE(?date_of_birth) AS ?date_of_birth) 
# (GROUP_CONCAT(DISTINCT ?country_of_citizenship; SEPARATOR=", ") AS ?country_of_citizenships)
# (GROUP_CONCAT(DISTINCT ?country_of_citizenshipLabel; SEPARATOR=", ") AS ?country_of_citizenshipLabels)

# (GROUP_CONCAT(DISTINCT ?occupation; SEPARATOR=", ") AS ?occupations)
# (GROUP_CONCAT(DISTINCT ?occupationLabel; SEPARATOR=", ") AS ?occupationLabels)

# (GROUP_CONCAT(DISTINCT ?country; SEPARATOR=", ") AS ?countries)
# (GROUP_CONCAT(DISTINCT ?countryLabel; SEPARATOR=", ") AS ?countryLabels)


# WHERE {
#   VALUES ?item {
#     wd:Q269809
#     wd:Q274590
#     wd:Q24576851
#     wd:Q807461
#     wd:Q4858963
#     wd:Q27954833
#     wd:Q4859015
#     wd:Q826930
#   }
#   OPTIONAL { ?item wdt:P18 ?pic. }
#   OPTIONAL { ?item wdt:P27 ?country_of_citizenship. }
#   OPTIONAL { ?item wdt:P106 ?occupation. }
#   OPTIONAL { ?item wdt:P17 ?country. }
#   OPTIONAL { ?item wdt:P569 ?date_of_birth. }
#   OPTIONAL { ?item wdt:P31 ?instance_of. }
#   OPTIONAL { ?item wdt:P17 ?country. }
#   OPTIONAL { ?item wdt:P569 ?date_of_birth. }
# }
# GROUP BY ?item