# #defaultView:BubbleChart
# #TEMPLATE={ "template": "The top 10 heaviest ?type ", "variables": { "?type": { "query": "SELECT DISTINCT ?id WHERE { ?i wdt:P2067 ?v. ?i wdt:P31 ?id}" } } }
# SELECT ?item  ?mass
# WHERE {
#   {
#     SELECT ?item ?mass WHERE {
#       ?item wdt:P31 wd:Q5;
#             p:P2067/psn:P2067/wikibase:quantityAmount ?mass.
#     }
#     ORDER BY DESC(?mass)
#     LIMIT 10
#   }
# }