#defaultView:BubbleChart
#title:Values of "uses" used in scholarly articles
# Demonstrates how to turn off the optimizer and start with the lowest number of edges first.
SELECT ?uses (count(?item) as ?c)
WHERE 
{
  ?item wdt:P2283 ?uses. # ~20,000 edges
  ?item wdt:P31 wd:Q13442814. # ~37M edges
}
group by ?uses
order by desc(?c)