# #added before 2016-10
# SELECT ?country ?countryLabel (count(*) AS ?count)
# WHERE
# {
# 	?city wdt:P31/wdt:P279* wd:Q515 . # find instances of subclasses of city
# 	?city p:P6 ?statement .           # with a P6 (head of goverment) statement
# 	?statement ps:P6 ?mayor .         # ... that has the value ?mayor
# 	?mayor wdt:P21 wd:Q6581072 .      # ... where the ?mayor has P21 (sex or gender) female
# 	FILTER NOT EXISTS { ?statement pq:P582 ?x }  # ... but the statement has no P582 (end date) qualifier
# 	?city wdt:P17 ?country .          # Also find the country of the city
 	
# }
# GROUP BY ?country ?countryLabel
# ORDER BY DESC(?count)
# LIMIT 100