#Show firearms cartridges and which they are based on
#defaultView:Graph
SELECT 
?item  ?image 
?other ?image2
WHERE
{
    ?item  wdt:P279+ wd:Q37144 .   # cartridges
    ?item  wdt:P144    ?other  .   # if the cartridge is based on another
    OPTIONAL {
      ?item  wdt:P18     ?image  .   # grab image
      ?other wdt:P18     ?image2 .   # grab image
    }
}