#defaultView:LineChart

SELECT  (str(?year) AS ?year) (AVG( ?_number_of_children ) AS ?count) WHERE {

  ?item wdt:P31 wd:Q5.

  ?item wdt:P1971 ?_number_of_children.

  ?item wdt:P569 ?_date_of_birth.

  BIND( year(?_date_of_birth) as ?year ).

  FILTER( ?year > 1900)

}



GROUP BY ?year