#defaultView:LineChart
SELECT ?country ?year ?AVGpopulation WHERE {
  {
    SELECT ?country ?year (AVG(?population) AS ?AVGpopulation) WHERE {
      {
        SELECT ?country (str(YEAR(?date)) AS ?year) ?population WHERE {
          ?country wdt:P47 wd:Q183;   # shares border with Germany
                   p:P1082 ?populationStatement.
          ?populationStatement ps:P1082 ?population;
                               pq:P585 ?date.
        }
      }
    }
    GROUP BY ?country ?year
  }
}