#defaultView:LineChart
SELECT ?year (COUNT(?_genre) AS ?count)  WHERE {
  ?item wdt:P31 wd:Q215380; # instance of: band
        wdt:P571 ?_date;   # inception
        wdt:P136 ?_genre.
  BIND(str(YEAR(?_date)) AS ?year)
  FILTER(?_date >= "1960-00-00T00:00:00Z"^^xsd:dateTime)
}
GROUP BY ?year
HAVING (?count > 10)