# #defaultView:Tree

# SELECT ?continent ?continentFlag ?continentLabel ?country ?countryLabel ?countryFlag ?region ?regionLabel ?regionFlag ?city ?cityLabel ?cityImage ?property ?propertyLabel ?value ?valueLabel WHERE {

#   {

#     SELECT * WHERE {

#       ?continent wdt:P31 wd:Q5107.

#       ?country wdt:P30 ?continent.

#       ?country p:P31/ps:P31 wd:Q6256.

#       ?country wdt:P150 ?region.

#       OPTIONAL {

#         ?continent wdt:P242 ?continentFlag.

#         ?country wdt:P41 ?countryFlag.

#         ?region wdt:P41 ?regionFlag.

#       }

#       OPTIONAL {

#         ?region wdt:P36 ?city.

#         ?city wdt:P31 wd:Q515.

#         ?city wdt:P18 ?cityImage.

#         OPTIONAL {

#           VALUES (?prop) {

#             (wdt:P1082)

#             (wdt:P6)

#             (wdt:P190)

#             (wdt:P31)

#             (wdt:P571)

#             (wdt:P150)

#             (wdt:P206)

#             (wdt:P527)

#           }

#           ?city ?prop ?value.

#           ?property ?ref ?prop.

#           ?property rdf:type wikibase:Property.

#         }

#       }

#     }

#   }

# }