#defaultView:Tree

SELECT ?composer ?composerImage ?tonality ?composition WHERE {

  ?composer wdt:P31 wd:Q5;

            wdt:P19|wdt:P20|wdt:P551 wd:Q1741.

  OPTIONAL { ?composer wdt:P18 ?composerImage. }

  ?composition wdt:P86 ?composer;

               wdt:P826 ?tonality.


}
