# #added before 2016-10

# #defaultView:TreeMap
# SELECT ?show ?showLabel  ?season ?cleanSeasonLabel ?episode ?episodeLabel
# WHERE
# {
# 	{
# 		BIND(wd:Q886 as ?show) .
# 		?season wdt:P361 ?show .
# 		?season rdfs:label ?_seasonLabel.
# 		FILTER((LANG(?_seasonLabel)) = "en")
# 		BIND(SUBSTR(?_seasonLabel, 0, STRLEN(?_seasonLabel)-23) AS ?cleanSeasonLabel)
# 		?episode wdt:P361 ?season .
# 	} 
# 	UNION
# 	{
# 		BIND(wd:Q16538 as ?show) .
# 		?season wdt:P361 ?show .
# 		?season rdfs:label ?_seasonLabel.
# 		FILTER((LANG(?_seasonLabel)) = "en")
# 		BIND(SUBSTR(?_seasonLabel, 0, STRLEN(?_seasonLabel)-20) AS ?cleanSeasonLabel)
# 		?episode wdt:P361 ?season .
# 	}  
# 	UNION
# 	{
# 		BIND(wd:Q147235 as ?show) .
# 		?season wdt:P361 ?show .
# 		?season rdfs:label ?_seasonLabel.
# 		FILTER((LANG(?_seasonLabel)) = "en")
# 		BIND(CONCAT("S", SUBSTR(?_seasonLabel, 25)) AS ?cleanSeasonLabel)
# 		?episode wdt:P361 ?season .
# 	}

# 	SERVICE wikibase:label {  bd:serviceParam wikibase:language "en" }
# }