#defaultView:ScatterChart

SELECT   ?year  (COUNT(?_genre) AS ?count )  (?year as ?year_shown) WHERE {

  ?item wdt:P31 wd:Q11424.

  ?item wdt:P577 ?_publication_date.

  ?item wdt:P136 ?_genre.

  BIND(str(YEAR(?_publication_date)) AS ?year)

 

 FILTER (?_publication_date >= "2000-00-00T00:00:00Z"^^xsd:dateTime)

}

GROUP BY ?year

HAVING (?count > 30)