# #defaultView:Map{"layer":"?instance_ofLabel"}
# SELECT ?place ?placeLabel ?image ?coordinate_location ?dist ?instance_of ?instance_ofLabel WHERE {
#   SERVICE wikibase:around {
#     ?place wdt:P625 ?coordinate_location.
#     bd:serviceParam wikibase:center "[AUTO_COORDINATES]".
#     bd:serviceParam wikibase:radius "1".
#     bd:serviceParam wikibase:distance ?dist.
#   }
#   
#   OPTIONAL { ?place wdt:P18 ?image. }
#   OPTIONAL { ?place wdt:P31 ?instance_of. }
# }