# Airports named after women
# List of airports that are named after women
# Written by WiseWoman auf der #wmdemv 2019
# defaultView:Map
SELECT DISTINCT ?airport ?coor ?namedafterLabel
WHERE {
  ?airport wdt:P31 wd:Q644371 ;  
          # ?range wd:Q183;
          wdt:P625 ?coor.
  ?airport wdt:P138 ?namedafter .
  ?namedafter wdt:P31 wd:Q5 .
  ?namedafter wdt:P21 wd:Q6581072 .
}