# #added before 2016-10
# #defaultView:Map
# SELECT DISTINCT ?item ?name ?coord ?lat ?lon
# WHERE {
#    hint:Query hint:optimizer "None" .
#    ?item wdt:P131* wd:Q61 .
#    ?item wdt:P31/wdt:P279* wd:Q33506 .
#    ?item wdt:P625 ?coord .
#    ?item p:P625 ?coordinate .
#    ?coordinate psv:P625 ?coordinate_node .
#    ?coordinate_node wikibase:geoLatitude ?lat .
#    ?coordinate_node wikibase:geoLongitude ?lon .
#    SERVICE wikibase:label {
#     bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" .
#     ?item rdfs:label ?name
#    }
# }
# ORDER BY ASC (?name)