#defaultView:Map
SELECT ?item ?coord #?lat ?lon
WHERE
{
   ?item               wdt:P31        wd:Q130003.
   ?item               wdt:P625         ?coord.

#  ?item                 p:P625         ?statementnode.
#  ?statementnode      psv:P625         ?valuenode.
#  ?valuenode     wikibase:geoLatitude  ?lat.
#  ?valuenode     wikibase:geoLongitude ?lon.

}