# #added before 2016-10
#  #sample from cywiki:Wicipedia:Merched_a_anwyd_yng_Nghymru
# SELECT ?item
# WHERE
# {
# 	# gender = female
#   	?item wdt:P21 wd:Q6581072 .

#   	# place of birth = Wales (Q25)
#   	{ ?item wdt:P19 wd:Q25 }
# 	# OR place of birth within Wales. This relies on places using P131 with Q25 ("Wales") as value (or with a value that has Q25 in P131)
# 	UNION  { ?item wdt:P19 ?pob . ?pob wdt:P131* wd:Q25 }

# 	# look for articles (sitelinks) in Welsh ("cy")
#   	OPTIONAL { ?sitelink schema:about ?item . ?sitelink schema:inLanguage "cy" }
# 	# but select items with no such article
# 	FILTER (!BOUND(?sitelink))

# 	# humans only
#   	?item wdt:P31 wd:Q5 .
# }
# #Listeria can only handle up to 5000
# LIMIT 1000