# #title: Getting pageviews for all articles in a category
# SELECT ?title ?pageviews ?date WHERE {
#   VALUES ?item { wd:Q16326821 } # Change category here
#   ?sitelink schema:about ?item ;
#             schema:isPartOf <https://en.wikipedia.org/> ; # To change language version first change here
#             schema:name ?name .
#   SERVICE wikibase:mwapi {
#     bd:serviceParam wikibase:api "Generator";
#                     wikibase:endpoint "en.wikipedia.org"; # then also change to the same language here
#                     mwapi:generator "categorymembers";
#                     mwapi:prop "pageviews";
#                     mwapi:gcmtitle ?name ;
#                     mwapi:pvipdays "1"; # How many days back in time to get the pageviews for
#                     mwapi:gcmlimit "500". # Max articles to get the results for
#     ?title wikibase:apiOutput mwapi:title .
#     ?pageviews wikibase:apiOutput "pageviews/pvip/text()".
#     ?date wikibase:apiOutput "pageviews/pvip/@date" .
#   }
#   FILTER(?pageviews != "1") # Filters out results with no views 
# } ORDER BY DESC(xsd:integer(?pageviews))