# #Combine the Wikidata Query Service and the OpenStreetMap Sophox query service
# PREFIX osmnode: <https://www.openstreetmap.org/node/>
# PREFIX osmway: <https://www.openstreetmap.org/way/>
# PREFIX osmrel: <https://www.openstreetmap.org/relation/>
# PREFIX osmt: <https://wiki.openstreetmap.org/wiki/Key:>
# PREFIX osmm: <https://www.openstreetmap.org/meta/>
# PREFIX pageviews: <https://dumps.wikimedia.org/other/pageviews/>
# PREFIX osmd: <http://wiki.openstreetmap.org/entity/>
# PREFIX osmdt: <http://wiki.openstreetmap.org/prop/direct/>
# PREFIX osmp: <http://wiki.openstreetmap.org/prop/>
# PREFIX osmps: <http://wiki.openstreetmap.org/prop/statement/>
# PREFIX osmpq: <http://wiki.openstreetmap.org/prop/qualifier/>

# SELECT * WHERE {
#   BIND(wd:Q28695 as ?wd)
#   SERVICE <https://sophox.org/sparql> {
#   ?osmid osmt:wikidata ?wd;
#          osmt:building ?building;
#          ?a ?b
#   }
# }