# #Get information of Europeana item using federated query
# PREFIX dc: <http://purl.org/dc/elements/1.1/>
# PREFIX edm: <http://www.europeana.eu/schemas/edm/>
# PREFIX ore: <http://www.openarchives.org/ore/terms/>

# SELECT * WHERE {
#   BIND(<http://data.europeana.eu/proxy/provider/91622/raa_kmb_16000200042758> as ?p854)  
#   SERVICE <http://sparql.europeana.eu/> {
#    {
#          ?p854 <http://purl.org/dc/terms/created> ?created .
#          ?p854 <http://purl.org/dc/elements/1.1/identifier> ?identifier .
#          ?p854 <http://purl.org/dc/elements/1.1/publisher> ?publisher .
#          ?p854 <http://purl.org/dc/elements/1.1/rights> ?rights .
#          ?p854 <http://purl.org/dc/elements/1.1/title> ?title .
#          ?p854 <http://purl.org/dc/elements/1.1/description> ?description .
#      }
#   }
# }