# #Get share of renewable energy in electricity using Federated query

# # Read share of renewable energy in electricity in EU countries from http://semantic.eea.europa.eu 
# # and populate the result with finnish and inari sami labels from Wikidata

# PREFIX cube: <http://purl.org/linked-data/cube#>
# PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#> 
# PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#> 
# PREFIX sdmx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#> 
# PREFIX property: <http://rdfdata.eionet.europa.eu/eurostat/property#> 

# SELECT DISTINCT
#    (YEAR(?timePeriod) as ?year)
#    (?obsValue as ?Share_of_renewable_energy_in_electricity)
#    ?unit_EN
#    ?unit_SMN
#    ?nuts
#    ?country_EN
#    ?country_SMN
#    ?flag
#    ?country
# WITH {
#    SELECT  * WHERE {

#       # Route query through zbw.eu as semantic.eea.europa.eu is not visible to query.wikidata.org

#       SERVICE <http://zbw.eu/beta/sparql/stw/query> {

#          # Read share of renewable energy in electricity in EU countries from http://semantic.eea.europa.eu 

#          SERVICE <http://semantic.eea.europa.eu/sparql> {
#             SELECT * WHERE {
#                ?row cube:dataSet <http://rdfdata.eionet.europa.eu/eurostat/data/nrg_ind_335a> .  
#                ?row property:indic_en  <http://dd.eionet.europa.eu/vocabulary/eurostat/indic_en/119820> .
#                ?row sdmx-dimension:timePeriod ?timePeriod .
#                ?row sdmx-measure:obsValue ?obsValue .
#                ?row sdmx-attribute:unitMeasure ?unitTmp .
#                ?row sdmx-dimension:refArea ?countryTmp .
#                ?countryTmp skos:prefLabel ?country_EN .
#                ?countryTmp skos:notation ?nuts .
#                ?unitTmp rdfs:label ?unit_EN .
#                FILTER(YEAR(?timePeriod) = 2016)
#             }
#          }
#       }
#    }
# }  AS %semantic_eea_europa_eu
# WHERE {
#    INCLUDE %semantic_eea_europa_eu .

#    # And populate the result with finnish and inari sami labels and flag from Wikidata

#    ?country wdt:P605 ?nuts .
#    ?country wdt:P41 ?flag .
#    ?unit wdt:P3328 ?unit_EN . 

#     OPTIONAL {?country rdfs:label ?country_FI FILTER (LANG(?country_FI) = "fi")}.
#     OPTIONAL {?country rdfs:label ?country_SMN FILTER (LANG(?country_SMN) = "smn")}.
#     OPTIONAL {?unit rdfs:label ?unit_FI FILTER (LANG(?unit_FI) = "fi")}.  
#     OPTIONAL {?unit rdfs:label ?unit_SMN FILTER (LANG(?unit_SMN) = "smn")}.   
  
#     FILTER(?country NOT IN (wd:Q756617, wd:Q29999)) # Filter out Kingdom Denmark and Kingdom of Netherlands
# }
# ORDER BY DESC(?Share_of_renewable_energy_in_electricity)
# LIMIT 35 # Expected number of results is 34