# # Get OpenStreetMap nodes with inarisami label in wikipedia but without inarisami label in OSM

# PREFIX osmt: <https://wiki.openstreetmap.org/wiki/Key:>
# PREFIX osmm: <https://www.openstreetmap.org/meta/>

# SELECT DISTINCT ?item_smn (?Label_fi as ?wd_label_fi) ?osm_name_fi ?Label_smn ?osm WITH {
# SELECT ?item_smn ?Label_smn ?coord_smn WHERE {
#  ?item_smn rdfs:label ?Label_smn filter (lang(?Label_smn) = "smn") .
#  ?item_smn wdt:P17 wd:Q33 .
#  ?item_smn wdt:P625 ?coord_smn .
# }
# } as %smn
# WHERE
# {
#  INCLUDE %smn . 
#  ?item_smn rdfs:label ?Label_fi filter (lang(?Label_fi) = "fi") .
#  ?item_smn wdt:P17 wd:Q33 .
#  ?item_smn wdt:P625 ?coord_smn .
#  FILTER(str(?Label_fi)!=str(?Label_smn))
  
#  SERVICE <https://sophox.org/sparql> { 
#     ?osm osmt:wikidata ?item_smn .
#     ?osm osmm:type "n".
#     ?osm osmt:name ?osm_name_fi .
#     FILTER NOT EXISTS { ?osm osmt:name:smn ?osm_name_smn }   
#   } 
# } 
# LIMIT 12001