# #added before 2016-10

# PREFIX entity: <http://www.wikidata.org/entity/>
# #partial results

# SELECT ?propUrl ?propLabel ?valUrl ?valLabel ?picture
# WHERE
# {
# 	hint:Query hint:optimizer 'None' .
# 	{	BIND(entity:Q42 AS ?valUrl) .
# 		BIND("N/A" AS ?propUrl ) .
# 		BIND("identity"@en AS ?propLabel ) .
# 	}
# 	UNION
# 	{	entity:Q42 ?propUrl ?valUrl .
# 		?property ?ref ?propUrl .
# 		?property rdf:type wikibase:Property .
# 		?property rdfs:label ?propLabel
# 	}
	
#   	?valUrl rdfs:label ?valLabel
# 	FILTER (LANG(?valLabel) = 'en') .
# 	OPTIONAL{ ?valUrl wdt:P18 ?picture .}
# 	FILTER (lang(?propLabel) = 'en' )
# }
# ORDER BY ?propUrl ?valUrl
# LIMIT 200